version: '3'

services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./app/frontend/DockerfileDev
  #   container_name: frontend
  #   tty: true
  #   stdin_open: true
  #   restart: always
  #   volumes:
  #     - ./app/frontend:/usr/app-front
  #   environment:
  #     - PORT=3000
  #     - APP_URL_SOCKET=http://localhost:3001
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - net

  api:
    build:
      context: .
      dockerfile: ./app/backend/DockerfileDev
    container_name: backend
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./app/backend:/usr/app-back
    environment:
      - PORT=3001
    ports:
      - 3001:3001
    networks:
      - net
  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    links:
      - mongo
    networks:
      - net

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./app/backend/db:/data/db
    networks:
      - net

networks:
  net:
    driver: bridge